plugins {
    id 'com.android.application'
}

def releaseStorePath = System.getenv('RELEASE_STORE_FILE')
def releaseSigningPassword = System.getenv('RELEASE_SIGNING_PASSWORD')

android {
    namespace 'io.github.blacktom222.hyperos4notificationimportance'
    compileSdk 35

    defaultConfig {
        applicationId 'io.github.blacktom222.hyperos4notificationimportance'
        minSdk 26
        targetSdk 35
        versionCode 7
        versionName '1.0.6'
    }

    signingConfigs {
        release {
            if (releaseStorePath && releaseSigningPassword) {
                storeFile file(releaseStorePath)
                storePassword releaseSigningPassword
                keyAlias 'hyperos4'
                keyPassword releaseSigningPassword
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            if (releaseStorePath && releaseSigningPassword) {
                signingConfig signingConfigs.release
            }
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError true
        checkReleaseBuilds true
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
}
