plugins {
    id 'com.android.application'
}

def releaseStorePath = System.getenv('RELEASE_STORE_FILE')
def releaseSigningPassword = System.getenv('RELEASE_SIGNING_PASSWORD')

android {
    namespace 'io.github.blacktom222.hyperos4notificationimportance'
    compileSdk 37

    defaultConfig {
        applicationId 'io.github.blacktom222.hyperos4notificationimportance'
        minSdk 26
        targetSdk 35
        versionCode 8
        versionName '1.1.0'
    }

    signingConfigs {
        release {
            if (releaseStorePath && releaseSigningPassword) {
                storeFile file(releaseStorePath)
                storePassword releaseSigningPassword
                keyAlias 'hyperos4'
                keyPassword releaseSigningPassword
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            if (releaseStorePath && releaseSigningPassword) {
                signingConfig signingConfigs.release
            }
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            merges += ['META-INF/xposed/*']
        }
    }

    lint {
        abortOnError true
        checkReleaseBuilds true
    }
}

dependencies {
    compileOnly 'io.github.libxposed:api:102.0.0'
    compileOnly 'androidx.annotation:annotation:1.10.0'
    implementation 'io.github.libxposed:service:102.0.0'
}
